### ISSUE TITLE
missing extensions?

### ISSUE THREAD

**Issue by davidseek** [bre7/mailgun-swift#1]
``` 
Value of type 'String' has no member 'split'
```

And

``` 
Value of type '[String : String]' has no member 'merge'
```

**Comment by davidseek** [comment]
it's Swift 4 isnt it?

https://developer.apple.com/documentation/swift/dictionary/2892855-merge

Xcode 9+

Wanted to avoid using Swift 4 till official release...

**Comment by bre7** [comment]
Hi David, Yeah, sorry I didn't include a warning in the readme. Let me check if I can push a swift 3 branch

**Comment by davidseek** [comment]
No problem. I have edited the missing parts to match Swift 3 syntax. Don't worry about it. The release is in like 2 weeks.

**Comment by bre7** [comment]
👍

**Comment by davidseek** [comment]
works just great. thank you for the project. might participate on it and help you out with your todo list. just too much work at the moment. but it's in my bookmarks :)
